name = "samsara-saga"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "samsarasaga"
database_id = "3a862404-843d-4427-8b30-0bbda1532a65"

[site]
bucket = "./public"

# Vectorize Index binding
[[vectorize]]
binding = "RAG_INDEX"
index_name = "samsara-rag"

# Workers AI binding
[ai]
binding = "AI"