main = ".svelte-kit/cloudflare/workers-site/index.js"
name = "samsara-saga"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "samsarasaga"
database_id = "3a862404-843d-4427-8b30-0bbda1532a65"

# Vectorize Index binding
[[vectorize]]
binding = "RAG_INDEX"
index_name = "samsara-rag"

# Workers AI binding
[ai]
binding = "AI"

[site]
bucket = ".svelte-kit/cloudflare"