name = "samsarasaga"
main = "index.mjs"
compatibility_date = "2024-07-25"

[site]
bucket = "./public"

# Vectorize Index binding
[[vectorize]]
binding = "RAG_INDEX"
index_name = "samsara-rag"

# Workers AI binding
[ai]
binding = "AI"